[package]
name = "llama2-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
memmap = "0.7.0"
rand = "0.8.5"
rayon = "1.7.0"
num_cpus = "1.16.0"
crabml = { git = "https://github.com/flaneur2020/crabml.git", commit = "910c4c6" }
